"""
Framework definitions for the metacoupling and telecoupling frameworks.

Contains enums, component definitions, and telecoupling categories derived
from Liu et al. (2013), Liu (2017), Liu (2023), and related literature.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class CouplingType(str, Enum):
    """Types of coupling in the metacoupling framework (Liu, 2017)."""

    INTRACOUPLING = "intracoupling"
    PERICOUPLING = "pericoupling"
    TELECOUPLING = "telecoupling"

    @property
    def description(self) -> str:
        return _COUPLING_DESCRIPTIONS[self]


_COUPLING_DESCRIPTIONS: dict[CouplingType, str] = {
    CouplingType.INTRACOUPLING: (
        "Human-nature interactions within a coupled human and natural system "
        "(Liu, 2017). The intracoupling framework focuses on interactions "
        "between human and nature subsystems within one focal system, through "
        "flows facilitated by agents, generated by causes, and leading to "
        "effects within both the focal system and any spillover systems."
    ),
    CouplingType.PERICOUPLING: (
        "Human-nature interactions between adjacent coupled human and natural "
        "systems (Liu, 2017). The pericoupling framework has the same "
        "structure as the telecoupling framework (systems, flows, agents, "
        "causes, effects) except that sending and receiving systems are "
        "nearby rather than far away. For example, flows of labor and "
        "materials between neighboring counties or nations."
    ),
    CouplingType.TELECOUPLING: (
        "Human-nature interactions between distant coupled human and natural "
        "systems (Liu et al., 2013). Telecoupling involves sending, receiving, "
        "and spillover systems connected by flows of information, energy, "
        "material, people, organisms, and capital across large geographic "
        "distances. Research shows that in many cases, telecouplings are "
        "stronger than pericouplings, challenging Tobler's First Law of "
        "Geography (Liu, 2023)."
    ),
}


class SystemRole(str, Enum):
    """Roles that a coupled human and natural system can play."""

    SENDING = "sending"
    RECEIVING = "receiving"
    SPILLOVER = "spillover"

    @property
    def description(self) -> str:
        return _SYSTEM_ROLE_DESCRIPTIONS[self]


_SYSTEM_ROLE_DESCRIPTIONS: dict[SystemRole, str] = {
    SystemRole.SENDING: (
        "A system that sends information, energy, material, people, "
        "organisms, and capital to other system(s). In intracoupling, "
        "the concept of sending system is not applicable — only the "
        "focal system is of interest (Liu, 2017, Table 1)."
    ),
    SystemRole.RECEIVING: (
        "A system that receives information, energy, material, people, "
        "organisms, and capital from sending system(s). In pericoupling, "
        "receiving systems are adjacent to sending systems; in telecoupling, "
        "they are distant (Liu, 2017, Table 1)."
    ),
    SystemRole.SPILLOVER: (
        "A system that is affected by or affects interactions between sending "
        "and receiving systems, even though it is not a direct participant. "
        "Spillover effects can be much larger than effects between sending "
        "and receiving systems (Liu, 2023). Spillover systems exist in all "
        "three coupling types and are often traditionally overlooked."
    ),
}


class FlowCategory(str, Enum):
    """Categories of flows between coupled systems (Liu, 2017, Table 1)."""

    CAPITAL = "capital"
    ENERGY = "energy"
    INFORMATION = "information"
    MATTER = "matter"
    ORGANISMS = "organisms"
    PEOPLE = "people"

    @property
    def description(self) -> str:
        return _FLOW_DESCRIPTIONS[self]


_FLOW_DESCRIPTIONS: dict[FlowCategory, str] = {
    FlowCategory.CAPITAL: (
        "Flows of money, investment, aid, financial resources, or economic "
        "value between systems (e.g., foreign direct investment, conservation "
        "funding, remittances, payments for ecosystem services, trade revenue)."
    ),
    FlowCategory.ENERGY: (
        "Flows of energy resources or energy embodied in traded goods "
        "between systems (e.g., electricity trade, embodied energy in "
        "exports, fossil fuel transfers)."
    ),
    FlowCategory.INFORMATION: (
        "Flows of knowledge, data, technology, ideas, and cultural "
        "practices between systems (e.g., technology transfer, scientific "
        "knowledge exchange, media, market signals)."
    ),
    FlowCategory.MATTER: (
        "Flows of physical goods, commodities, natural resources, water, "
        "waste, and other material substances between systems (e.g., "
        "soybean trade, water transfer, e-waste shipments, dust transport)."
    ),
    FlowCategory.ORGANISMS: (
        "Flows of living organisms between systems, including both "
        "intentional transfers and natural movements (e.g., species "
        "invasion, seed dispersal, animal migration, livestock trade, "
        "pathogen spread)."
    ),
    FlowCategory.PEOPLE: (
        "Flows of people between systems for economic, political, "
        "environmental, or recreational reasons (e.g., migration, "
        "tourism, labor movement, refugees)."
    ),
}


class AgentLevel(str, Enum):
    """Fixed agent categories used by MetacouplingAssistant."""

    INDIVIDUALS_HOUSEHOLDS = "individuals / households"
    FIRMS_TRADERS_CORPORATIONS = "firms / traders / corporations"
    GOVERNMENTS_POLICYMAKERS = "governments / policymakers"
    ORGANIZATIONS_NGOS = "organizations / NGOs"
    NON_HUMAN_AGENTS = "non-human agents"
    # Backward-compatible enum aliases; iteration still yields only the
    # fixed categories above.
    INDIVIDUAL = "individuals / households"
    HOUSEHOLD = "individuals / households"
    COMPANY = "firms / traders / corporations"
    ORGANIZATION = "organizations / NGOs"
    GOVERNMENT = "governments / policymakers"

    @property
    def description(self) -> str:
        return _AGENT_LEVEL_DESCRIPTIONS[self]


_AGENT_LEVEL_DESCRIPTIONS: dict[AgentLevel, str] = {
    AgentLevel.INDIVIDUALS_HOUSEHOLDS: (
        "Individual people and household units that make decisions affecting "
        "coupling processes, such as farmers, consumers, tourists, migrants, "
        "fishers, local residents, and farming households."
    ),
    AgentLevel.FIRMS_TRADERS_CORPORATIONS: (
        "Private-sector actors that produce, trade, finance, transport, or "
        "market flows, including firms, traders, corporations, processors, "
        "exporters, importers, logistics companies, and tourism operators."
    ),
    AgentLevel.GOVERNMENTS_POLICYMAKERS: (
        "Government agencies, elected officials, regulators, and policymakers "
        "that shape coupling processes through policy, planning, enforcement, "
        "diplomacy, public investment, and institutional authority."
    ),
    AgentLevel.ORGANIZATIONS_NGOS: (
        "Non-governmental, civil-society, research, nonprofit, and "
        "intergovernmental organizations, including NGOs, universities, "
        "certification bodies, community organizations, and international bodies."
    ),
    AgentLevel.NON_HUMAN_AGENTS: (
        "Non-human entities that actively mediate or drive coupling dynamics, "
        "such as migratory animals, invasive species, pathogens, pests, crops, "
        "livestock, or other organisms when they function as agents rather "
        "than only as flows or affected components."
    ),
}


class CauseCategory(str, Enum):
    """Fixed cause categories used by MetacouplingAssistant."""

    ECONOMIC = "economic"
    POLITICAL_INSTITUTIONAL = "political / institutional"
    ECOLOGICAL_BIOLOGICAL = "ecological / biological"
    TECHNOLOGICAL_INFRASTRUCTURAL = "technological / infrastructural"
    CULTURAL_SOCIAL_DEMOGRAPHIC = "cultural / social / demographic"
    HYDROLOGICAL = "hydrological"
    CLIMATIC_ATMOSPHERIC = "climatic / atmospheric"
    GEOLOGICAL_GEOMORPHOLOGICAL = "geological / geomorphological"
    # Backward-compatible enum aliases; iteration still yields only the
    # fixed categories above.
    SOCIOECONOMIC = "economic"
    POLITICAL = "political / institutional"
    ECOLOGICAL = "ecological / biological"
    CULTURAL = "cultural / social / demographic"
    GEOLOGICAL = "geological / geomorphological"

    @property
    def description(self) -> str:
        return _CAUSE_EFFECT_CATEGORY_DESCRIPTIONS[self.value]


class EffectCategory(str, Enum):
    """Fixed effect categories used by MetacouplingAssistant."""

    ECONOMIC = "economic"
    POLITICAL_INSTITUTIONAL = "political / institutional"
    ECOLOGICAL_BIOLOGICAL = "ecological / biological"
    TECHNOLOGICAL_INFRASTRUCTURAL = "technological / infrastructural"
    CULTURAL_SOCIAL_DEMOGRAPHIC = "cultural / social / demographic"
    HYDROLOGICAL = "hydrological"
    CLIMATIC_ATMOSPHERIC = "climatic / atmospheric"
    GEOLOGICAL_GEOMORPHOLOGICAL = "geological / geomorphological"
    # Backward-compatible enum aliases; iteration still yields only the
    # fixed categories above.
    SOCIOECONOMIC = "economic"
    POLITICAL = "political / institutional"
    ECOLOGICAL = "ecological / biological"
    BIOLOGICAL = "ecological / biological"
    BIOGEOCHEMICAL = "climatic / atmospheric"
    CULTURAL = "cultural / social / demographic"
    GEOLOGICAL = "geological / geomorphological"

    @property
    def description(self) -> str:
        return _CAUSE_EFFECT_CATEGORY_DESCRIPTIONS[self.value]


_CAUSE_EFFECT_CATEGORY_DESCRIPTIONS: dict[str, str] = {
    "economic": (
        "Economic drivers or outcomes, including markets, prices, income, "
        "employment, livelihoods, trade revenue, investment, costs, poverty, "
        "inequality, and sectoral growth."
    ),
    "political / institutional": (
        "Political and institutional drivers or outcomes, including policies, "
        "regulations, governance, institutions, enforcement, diplomacy, "
        "property rights, subsidies, agreements, and planning decisions."
    ),
    "ecological / biological": (
        "Ecological and biological drivers or outcomes, including ecosystem "
        "processes, biodiversity, habitat change, species distributions, "
        "invasive species, pests, pathogens, and ecosystem services."
    ),
    "technological / infrastructural": (
        "Technological and infrastructural drivers or outcomes, including "
        "innovation, production technologies, roads, ports, dams, logistics, "
        "processing facilities, monitoring systems, and technical capacity."
    ),
    "cultural / social / demographic": (
        "Cultural, social, and demographic drivers or outcomes, including "
        "values, traditions, social norms, diets, migration, population "
        "change, consumption preferences, public health, and well-being."
    ),
    "hydrological": (
        "Water-related drivers or outcomes, including water availability, "
        "water quality, runoff, watershed dynamics, groundwater, drought, "
        "flooding, irrigation, and river-flow alteration."
    ),
    "climatic / atmospheric": (
        "Climate and atmosphere-related drivers or outcomes, including "
        "temperature, precipitation, drought risk, greenhouse gas emissions, "
        "air pollution, atmospheric transport, wind, and climate change."
    ),
    "geological / geomorphological": (
        "Geological and geomorphological drivers or outcomes, including "
        "soils, terrain, erosion, sedimentation, mineral deposits, tectonic "
        "activity, landslides, and landform change."
    ),
}


class FrameworkComponent(str, Enum):
    """The five major components of the telecoupling framework."""

    SYSTEMS = "systems"
    FLOWS = "flows"
    AGENTS = "agents"
    CAUSES = "causes"
    EFFECTS = "effects"


# ---------------------------------------------------------------------------
# Component Definitions
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ComponentDefinition:
    """Definition of a framework component with guiding questions."""

    name: str
    description: str
    sub_elements: list[str] = field(default_factory=list)
    guiding_questions: list[str] = field(default_factory=list)


COMPONENT_DEFINITIONS: dict[FrameworkComponent, ComponentDefinition] = {
    FrameworkComponent.SYSTEMS: ComponentDefinition(
        name="Systems",
        description=(
            "Coupled human and natural systems involved in the interaction. "
            "Each system contains both a human (socioeconomic) subsystem and "
            "a natural (environmental/ecological) subsystem that interact with "
            "each other. Systems are classified by their role: sending, receiving, "
            "or spillover."
        ),
        sub_elements=[
            "Sending system(s) — origin of flows",
            "Receiving system(s) — destination of flows",
            "Spillover system(s) — indirectly affected systems",
            "Human subsystem within each system (governance, economy, society)",
            "Natural subsystem within each system (ecosystems, biodiversity, climate)",
        ],
        guiding_questions=[
            "What are the coupled human and natural systems involved?",
            "Which system(s) send flows and which receive them?",
            "Are there spillover systems affected indirectly?",
            "What are the human and natural subsystems within each system?",
            "Can system roles change over time or be bidirectional?",
        ],
    ),
    FrameworkComponent.FLOWS: ComponentDefinition(
        name="Flows",
        description=(
            "Movements of matter, energy, information, capital, organisms, "
            "or people between systems (Liu, 2017, Table 1). Flows are what "
            "connect the coupled systems and can be unidirectional or "
            "bidirectional."
        ),
        sub_elements=[
            "Capital flows (investment, aid, payments, remittances, trade revenue)",
            "Energy flows (electricity, embodied energy, fossil fuels)",
            "Information flows (knowledge, technology, data, cultural practices)",
            "Matter flows (goods, commodities, water, waste, natural resources)",
            "Organism flows (species invasion, seed dispersal, animal migration)",
            "People flows (migration, tourism, labor movement, refugees)",
        ],
        guiding_questions=[
            "What is being transferred between systems?",
            "What categories do the flows belong to (capital, energy, information, "
            "matter, organisms, people)?",
            "What is the direction and magnitude of each flow?",
            "Are flows unidirectional or bidirectional?",
            "How have flows changed over time?",
        ],
    ),
    FrameworkComponent.AGENTS: ComponentDefinition(
        name="Agents",
        description=(
            "Autonomous decision-making entities that directly or indirectly "
            "facilitate or hinder coupling processes. Agents are grouped "
            "into five fixed categories: individuals / households; firms / "
            "traders / corporations; governments / policymakers; "
            "organizations / NGOs; and non-human agents."
        ),
        sub_elements=[
            "Individuals / households (farmers, consumers, tourists, migrants, fishers, local residents)",
            "Firms / traders / corporations (agribusinesses, exporters, importers, logistics companies)",
            "Governments / policymakers (public agencies, regulators, elected officials, planning bodies)",
            "Organizations / NGOs (NGOs, universities, certification bodies, international organizations)",
            "Non-human agents (migratory animals, invasive species, pathogens, pests, crops, livestock)",
            "Agents in sending systems",
            "Agents in receiving systems",
            "Agents facilitating the coupling (brokers, intermediaries)",
        ],
        guiding_questions=[
            "Who or what drives the interactions between systems?",
            "What agents exist in the sending, receiving, and spillover systems?",
            "Which fixed agent category does each agent belong to?",
            "What are the agents' motivations and decision-making processes?",
            "How do different agent categories interact?",
            "Are there intermediary agents facilitating the telecoupling?",
            "Are any non-human entities active agents rather than only flows or affected resources?",
        ],
    ),
    FrameworkComponent.CAUSES: ComponentDefinition(
        name="Causes",
        description=(
            "Factors that drive coupling processes, grouped into the fixed "
            "MetacouplingAssistant cause/effect categories."
        ),
        sub_elements=[
            "Economic causes (markets, prices, demand, investment, costs)",
            "Political / institutional causes (policies, governance, regulation, institutions)",
            "Ecological / biological causes (ecosystem processes, species, habitat, pests)",
            "Technological / infrastructural causes (technology, roads, ports, logistics, dams)",
            "Cultural / social / demographic causes (values, diets, migration, population change)",
            "Hydrological causes (water availability, water quality, drought, flooding)",
            "Climatic / atmospheric causes (climate variability, emissions, air transport)",
            "Geological / geomorphological causes (soils, terrain, erosion, deposits)",
        ],
        guiding_questions=[
            "What economic forces drive the coupling?",
            "What political or institutional conditions drive the coupling?",
            "What ecological or biological processes contribute to the interaction?",
            "What technological or infrastructural factors enable or constrain it?",
            "What cultural, social, or demographic factors are involved?",
            "What hydrological conditions play a role?",
            "What climatic or atmospheric conditions play a role?",
            "What geological or geomorphological conditions are involved?",
            "How do causes differ between sending and receiving systems?",
            "Are there external/global causes (e.g., international policy, climate change)?",
        ],
    ),
    FrameworkComponent.EFFECTS: ComponentDefinition(
        name="Effects",
        description=(
            "Consequences and outcomes of coupling processes on coupled "
            "human and natural systems, grouped into the fixed "
            "MetacouplingAssistant cause/effect categories. Effects can be "
            "positive, negative, or mixed for each system."
        ),
        sub_elements=[
            "Economic effects (income, employment, costs, market shifts)",
            "Political / institutional effects (governance, regulation, enforcement)",
            "Ecological / biological effects (biodiversity, habitat, species, ecosystem services)",
            "Technological / infrastructural effects (infrastructure, innovation, logistics)",
            "Cultural / social / demographic effects (well-being, migration, equity, norms)",
            "Hydrological effects (water quantity, quality, runoff, watershed change)",
            "Climatic / atmospheric effects (GHG emissions, air pollution, climate feedbacks)",
            "Geological / geomorphological effects (soil change, erosion, sedimentation)",
            "Synergies and tradeoffs between effects",
            "Feedback effects (how effects alter causes or flows)",
        ],
        guiding_questions=[
            "Which fixed effect categories are relevant for each system?",
            "Are effects positive, negative, or mixed for each system?",
            "How do effects on sending vs. receiving systems compare?",
            "What spillover effects occur on third-party systems?",
            "Are there feedback loops where effects alter causes or flows?",
            "What synergies or tradeoffs exist among the effects?",
        ],
    ),
}


# ---------------------------------------------------------------------------
# Telecoupling Categories
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class TelecouplingCategory:
    """A recognized category of telecoupling from Liu et al. (2013)."""

    name: str
    description: str
    example: str
    keywords: list[str] = field(default_factory=list)


TELECOUPLING_CATEGORIES: list[TelecouplingCategory] = [
    TelecouplingCategory(
        name="Trade",
        description=(
            "International or long-distance exchange of goods and commodities "
            "that connects distant production and consumption systems."
        ),
        example="Brazil-to-China soybean trade driving deforestation and land-use change",
        keywords=["trade", "export", "import", "commodity", "market", "commerce"],
    ),
    TelecouplingCategory(
        name="Development investment",
        description=(
            "Foreign direct investment and development projects that connect "
            "investor and host country systems."
        ),
        example="Chinese investment in African agricultural and mining projects",
        keywords=["investment", "development", "FDI", "foreign", "economic"],
    ),
    TelecouplingCategory(
        name="Transnational land transfer",
        description=(
            "Large-scale acquisition or lease of land in one country by "
            "entities from another country (land grabbing)."
        ),
        example="Saudi Arabia leasing farmland in Ethiopia for food production",
        keywords=["land", "acquisition", "lease", "transnational", "grabbing"],
    ),
    TelecouplingCategory(
        name="Conservation investment",
        description=(
            "Financial and institutional flows for biodiversity conservation "
            "and environmental protection across distant systems."
        ),
        example="International funding for tropical rainforest conservation",
        keywords=["conservation", "protected", "biodiversity", "funding", "PES",
                   "ecosystem services", "wildlife"],
    ),
    TelecouplingCategory(
        name="Technology transfer",
        description=(
            "Movement of technology, equipment, and technical capacity between "
            "distant systems."
        ),
        example="Transfer of renewable energy technology from developed to developing nations",
        keywords=["technology", "innovation", "transfer", "technical", "equipment"],
    ),
    TelecouplingCategory(
        name="Knowledge transfer",
        description=(
            "Exchange of scientific knowledge, educational resources, and "
            "expertise between distant systems."
        ),
        example="International research collaborations on climate change adaptation",
        keywords=["knowledge", "research", "education", "science", "academic",
                   "collaboration"],
    ),
    TelecouplingCategory(
        name="Human migration",
        description=(
            "Movement of people between distant systems for economic, "
            "political, or environmental reasons."
        ),
        example="Rural-to-urban migration from agricultural regions to industrial cities",
        keywords=["migration", "refugee", "immigration", "emigration", "diaspora",
                   "labor", "displacement"],
    ),
    TelecouplingCategory(
        name="Tourism",
        description=(
            "Travel of people between distant systems for recreation, "
            "creating socioeconomic and environmental impacts in both "
            "origin and destination systems."
        ),
        example="International ecotourism to panda reserves in China",
        keywords=["tourism", "travel", "ecotourism", "visitor", "recreation"],
    ),
    TelecouplingCategory(
        name="Waste transfer",
        description=(
            "Movement of waste, pollutants, or discarded materials between "
            "distant systems."
        ),
        example="International e-waste shipments from developed to developing countries",
        keywords=["waste", "pollution", "e-waste", "garbage", "disposal", "toxic"],
    ),
    TelecouplingCategory(
        name="Species invasion",
        description=(
            "Introduction and spread of non-native species between distant "
            "systems, often facilitated by trade or transport."
        ),
        example="Red imported fire ant invasion from USA to China via shipping containers",
        keywords=["invasive", "species", "invasion", "non-native", "alien", "pest",
                   "biological"],
    ),
    TelecouplingCategory(
        name="Animal migration",
        description=(
            "Natural seasonal or life-cycle movement of animal species "
            "between distant systems."
        ),
        example="Migratory bird flyways connecting breeding and wintering habitats",
        keywords=["migration", "migratory", "bird", "flyway", "seasonal", "wildlife"],
    ),
    TelecouplingCategory(
        name="Water transfer",
        description=(
            "Engineered or natural movement of water resources between "
            "distant systems, including inter-basin transfers and virtual water."
        ),
        example="South-to-North Water Transfer Project in China supplying Beijing",
        keywords=["water", "transfer", "irrigation", "dam", "basin", "virtual water",
                   "hydrological"],
    ),
    TelecouplingCategory(
        name="Species dispersal",
        description=(
            "Natural spread and distribution of species between distant "
            "systems through ecological processes."
        ),
        example="Seed dispersal by migratory animals connecting forest ecosystems",
        keywords=["dispersal", "spread", "seed", "propagule", "colonization",
                   "distribution"],
    ),
    TelecouplingCategory(
        name="Atmospheric circulation",
        description=(
            "Large-scale movement of atmospheric components (dust, pollutants, "
            "moisture) between distant systems."
        ),
        example="Saharan dust transport to the Amazon Basin fertilizing soils",
        keywords=["atmospheric", "air", "dust", "pollution", "climate", "wind",
                   "aerosol", "carbon"],
    ),
]


# ---------------------------------------------------------------------------
# Knowledge Formatter
# ---------------------------------------------------------------------------

def get_framework_knowledge() -> str:
    """Return a formatted string of all framework knowledge for prompt injection.

    This produces a comprehensive text block covering:
    - Metacoupling framework overview (intracoupling, pericoupling, telecoupling)
    - The five components with definitions and guiding questions
    - The 14 telecoupling categories with examples
    """
    sections: list[str] = []

    # --- Metacoupling overview ---
    sections.append("## METACOUPLING FRAMEWORK OVERVIEW\n")
    sections.append(
        "The metacoupling framework (Liu, 2017) is an integrated framework for "
        "understanding human-nature interactions across all spatial scales. It "
        "encompasses three types of couplings:\n"
    )
    for ct in CouplingType:
        sections.append(f"- **{ct.value.title()}**: {ct.description}\n")
    sections.append(
        "\nA coupled human and natural system (CHANS) contains interconnected "
        "human (socioeconomic) and natural (environmental/ecological) components "
        "that interact with each other.\n"
    )

    # --- Five components ---
    sections.append("\n## FIVE FRAMEWORK COMPONENTS\n")
    sections.append(
        "The telecoupling framework (Liu et al., 2013) identifies five "
        "interrelated components for analyzing distant human-nature interactions:\n"
    )
    for comp, defn in COMPONENT_DEFINITIONS.items():
        sections.append(f"\n### {defn.name}\n")
        sections.append(f"{defn.description}\n")
        sections.append("\nSub-elements:")
        for sub in defn.sub_elements:
            sections.append(f"  - {sub}")
        sections.append("\nGuiding questions:")
        for q in defn.guiding_questions:
            sections.append(f"  - {q}")
        sections.append("")

    # --- 14 telecoupling categories ---
    sections.append("\n## TELECOUPLING CATEGORIES\n")
    sections.append(
        "Liu et al. (2013) identified 14 major categories of telecoupling. "
        "A single study may involve one or more of these categories:\n"
    )
    for i, cat in enumerate(TELECOUPLING_CATEGORIES, 1):
        sections.append(f"{i}. **{cat.name}**: {cat.description}")
        sections.append(f"   Example: {cat.example}\n")

    # --- Key insights from Liu (2017) and Liu (2023) ---
    sections.append("\n## KEY ANALYTICAL INSIGHTS\n")

    sections.append("### Operationalization Procedure (Liu, 2017)\n")
    sections.append(
        "Operationalizing the metacoupling framework involves six phases:\n"
        "  1. Set research goals — formulate objectives, questions, hypotheses\n"
        "  2. Define focal system(s) — determined by research goals and feasibility\n"
        "  3. Review literature / conduct studies on flows, agents, causes, effects — "
        "trace flows across space to determine system boundaries\n"
        "  4. Finalize system boundaries — where flows start and end define boundaries; "
        "entities affecting flows are agents; reasons for flows are causes\n"
        "  5. Collect and analyze data — quantitative and qualitative\n"
        "  6. Communicate results — publications, stakeholder engagement\n"
    )

    sections.append("### Coupling Transformations (Liu, 2023)\n")
    sections.append(
        "Systems can undergo four stages of transformation:\n"
        "  - Noncoupling: no human-nature interactions within or between systems\n"
        "  - Coupling: interactions emerge among components\n"
        "  - Decoupling: interactions weaken or dissolve (e.g., due to shocks "
        "like economic recession, pandemic, or war)\n"
        "  - Recoupling: weakened or dissolved interactions are recovered\n"
        "These stages can occur in intracoupling, pericoupling, and telecoupling "
        "simultaneously or separately.\n"
    )

    sections.append("### Complex Interactions Among Coupling Types (Liu, 2023)\n")
    sections.append(
        "  - Intracoupling, pericoupling, and telecoupling can have synergistic effects\n"
        "  - Pericoupling and telecoupling can amplify intracoupling\n"
        "  - Increases in one type of coupling may reduce other types\n"
        "  - One type of coupling may generate benefits on one scale at the cost "
        "of other scales (spatial tradeoffs)\n"
        "  - Telecoupling, pericoupling, and intracoupling can interact indirectly\n"
        "  - Feedbacks (positive or negative) are common and may take time to emerge\n"
    )

    sections.append("### Cascading Interactions (Liu, 2023)\n")
    sections.append(
        "An event in one place can cascade and spread impacts on other places "
        "both nearby and far away through multiple steps. For example, drought in "
        "the US Midwest reduced soybean production, potentially increasing global "
        "soybean prices, which could encourage deforestation in Brazil for expanded "
        "soybean cultivation.\n"
    )

    sections.append("### Flow-Based Governance (Liu, 2023)\n")
    sections.append(
        "The framework supports shifting from place-based governance (focus on "
        "specific places independently) to flow-based governance (focus on movements "
        "of people, information, energy, matter, organisms, goods, capital among "
        "places). This shift can enhance global sustainability and improve spatial "
        "justice and equity.\n"
    )

    return "\n".join(sections)
